version: "3" 
services:
    nginx:
        image: nginx
        volumes:
            #- ./docker/nginx/default-apache.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/default-php-fpm.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/mongo-express.conf:/etc/ngidnx/conf.d/mongo-express.conf
            - ./docker/nginx/phpmyadmin.conf:/etc/nginx/conf.d/phpmyadmin.conf
            - ./app:/var/www/app
        ports:
            - "80:80"
    php-fpm:
        #build:
        #            context: ./docker/php-fpm
        image: test1_php-fpm
        volumes:
            - ./app:/var/www/app
            - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            APACHE_DOCUMENT_ROOT: "public/"
            PHP_EXTENSION_XDEBUG: "1"
            PHP_INI_MEMORY_LIMIT: "1G"
            # Symfony
            APP_ENV: "dev"
            APP_SECRET: "1fd2d4c91f5cbf4e3d4714888a88b349"
            DATABASE_URL: "mysql://$MYSQL_USER:$MYSQL_PASSWORD@mysql:3306/$MYSQL_DATABASE"
        #ports:
        #    - "9000:9000"
    mysql:
        image: mysql:5.7
        #restart: always
        #command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data2:/var/lib/mysql
        environment:
               MYSQL_ROOT_PASSWORD: "$MYSQL_ROOT_PASSWORD"
               MYSQL_DATABASE: "$MYSQL_DATABASE"
               MYSQL_USER: "$MYSQL_USER"
               MYSQL_PASSWORD: "$MYSQL_PASSWORD"
    mysql_tests:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: "admin"
            MYSQL_DATABASE: "tests"
            MYSQL_USER: "foo"
            MYSQL_PASSWORD: "bar"
        volumes:
            - ./docker/mysql_test/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: "mysql"
            PMA_USER: "$MYSQL_USER"
            PMA_PASSWORD: "$MYSQL_PASSWORD"
        volumes:
            - /sessions
        #ports:
        #    - "443:80"
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./docker/mongo/data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: "$MONGO_INITDB_ROOT_USERNAME"
            MONGO_INITDB_ROOT_PASSWORD: "$MONGO_INITDB_ROOT_PASSWORD"
            MONGO_INITDB_DATABASE: "$MONGO_INITDB_DATABASE"
    mongo-express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
            #ME_CONFIG_MONGODB_AUTH_USERNAME: "$MONGO_INITDB_ROOT_USERNAME"
            #ME_CONFIG_MONGODB_AUTH_PASSWOR: "$MONGO_INITDB_ROOT_PASSWORD"
            #ME_CONFIG_BASICAUTH_USERNAME: "$MONGO_INITDB_ROOT_USERNAME"
            #ME_CONFIG_BASICAUTH_PASSWORD: "$MONGO_INITDB_ROOT_PASSWORD"
            ME_CONFIG_MONGODB_AUTH_DATABASE: "$MONGO_INITDB_DATABASE"
            ME_CONFIG_MONGODB_ADMINUSERNAME: "$MONGO_INITDB_ROOT_USERNAME"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "$MONGO_INITDB_ROOT_PASSWORD"
        ports:
            - "8081:8081"
    memcashed:
        image: memcached:latest
        ports:
            - "11211:11211"